-- BimmerTech Firmware — seed data
-- Run this AFTER the migration: php bin/console doctrine:migrations:migrate
-- Then: mysql -u root -p app < seed.sql  (adjust credentials to match your .env)

INSERT INTO software_version (name, system_version, system_version_alt, link, st, gd, latest)
VALUES ('MMI Prime CIC', 'v3.1.1.2.mmi.c', '3.1.1.2.mmi.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.1.1.4.mmi.c', '3.1.1.4.mmi.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.1.1.4t.mmi.c', '3.1.1.4t.mmi.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.1.1.5t.mmi.c', '3.1.1.5t.mmi.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.1.1.6s.mmi.c', '3.1.1.6s.mmi.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.1.1.7.mmi.c', '3.1.1.7.mmi.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.1.1.7R4.mmi.c', '3.1.1.7R4.mmi.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.1.1.8.mmi.c', '3.1.1.8.mmi.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.1.1.8R4.mmi.c', '3.1.1.8R4.mmi.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.1.1.9.mmipri.c', '3.1.1.9.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.2.0.mmipri.c', '3.2.0.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.3.0.mmipri.c', '3.3.0.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.3.1.mmipri.c', '3.3.1.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.3.2.mmipri.c', '3.3.2.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.3.3.mmipri.c', '3.3.3.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.3.4.mmipri.c', '3.3.4.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.3.5.mmipri.c', '3.3.5.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.3.6.mmipri.c', '3.3.6.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE',
        'https://drive.google.com/drive/folders/1wXfribAWWliCvUMQEtdDrnki3he9EKCK', NULL, 0),
       ('MMI Prime CIC', 'v3.3.7.mmipri.c', '3.3.7.mmipri.c',
        'https://drive.google.com/drive/folders/1SRkHReNFxeAl6mXzOiwyXcdv9CIdPWyE', NULL, NULL, 1),
       ('MMI Prime NBT', 'v3.1.1.4.mmi.b', '3.1.1.4.mmi.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.1.1.4t.mmi.b', '3.1.1.4t.mmi.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.1.1.5t.mmi.b', '3.1.1.5t.mmi.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.1.1.5t4.mmi.b', '3.1.1.5t4.mmi.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.1.1.6s.mmi.b', '3.1.1.6s.mmi.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.1.1.7.mmi.b', '3.1.1.7.mmi.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.1.1.7R4.mmi.b', '3.1.1.7R4.mmi.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.1.1.8.mmi.b', '3.1.1.8.mmi.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.1.1.8R4.mmi.b', '3.1.1.8R4.mmi.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.1.1.9.mmipri.b', '3.1.1.9.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.2.0.mmipri.b', '3.2.0.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.3.0.mmipri.b', '3.3.0.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.3.1.mmipri.b', '3.3.1.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.3.2.mmipri.b', '3.3.2.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.3.3.mmipri.b', '3.3.3.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.3.4.mmipri.b', '3.3.4.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.3.5.mmipri.b', '3.3.5.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.3.6.mmipri.b', '3.3.6.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL',
        'https://drive.google.com/drive/folders/1Bk3ZdyrpsWRT0R3fN7jCYEhnRT1YcEYg',
        'https://drive.google.com/drive/folders/1Rv6pVyo2qy0rAIkEVUFJwyItWsRLuiuE', 0),
       ('MMI Prime NBT', 'v3.3.7.mmipri.b', '3.3.7.mmipri.b',
        'https://drive.google.com/drive/folders/1PyoGrao0HT1Nh9RIlYiEoYIODF9xgoJL', NULL, NULL, 1),
       ('MMI Prime EVO', 'v3.1.1.2.mmi.e', '3.1.1.2.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.4.mmi.e', '3.1.1.4.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.4t1.mmi.e', '3.1.1.4t1.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.5t.mmi.e', '3.1.1.5t.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.6.mmi.e', '3.1.1.6.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.6s.mmi.e', '3.1.1.6s.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.7.mmi.e', '3.1.1.7.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.7R4.mmi.e', '3.1.1.7R4.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.8.mmi.e', '3.1.1.8.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.8R4.mmi.e', '3.1.1.8R4.mmi.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.1.1.9.mmipri.e', '3.1.1.9.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.2.0.mmipri.e', '3.2.0.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.3.0.mmipri.e', '3.3.0.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.3.1.mmipri.e', '3.3.1.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.3.2.mmipri.e', '3.3.2.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.3.3.mmipri.e', '3.3.3.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.3.4.mmipri.e', '3.3.4.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.3.5.mmipri.e', '3.3.5.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.3.6.mmipri.e', '3.3.6.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS',
        'https://drive.google.com/drive/folders/1B6xGokuf5pzV1Y4qZBYlcQ-8uK99Yfff',
        'https://drive.google.com/drive/folders/1L7Uj4H4La8OMguKGtI0M0b4_DZcFqDlU', 0),
       ('MMI Prime EVO', 'v3.3.7.mmipri.e', '3.3.7.mmipri.e',
        'https://drive.google.com/drive/folders/1F8hm9jIN9vPwxEv2Dqk9ABBxZoqrSQyS', NULL, NULL, 1),
       ('MMI PRO CIC', 'v3.1.1.8R1.mmipro.c', '3.1.1.8R1.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.1.1.8R3.mmipro.c', '3.1.1.8R3.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.1.1.8R4.mmipro.c', '3.1.1.8R4.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.1.1.9.mmipro.c', '3.1.1.9.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.2.0.mmipro.c', '3.2.0.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.3.0.mmipro.c', '3.3.0.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.3.1.mmipro.c', '3.3.1.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.3.2.mmipro.c', '3.3.2.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.3.3.mmipro.c', '3.3.3.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.3.4.mmipro.c', '3.3.4.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.3.5.mmipro.c', '3.3.5.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.3.6.mmipro.c', '3.3.6.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ',
        'https://drive.google.com/drive/folders/1tP5HBhEgZnS4e8boX4MNut1ZZMtObfwD', NULL, 0),
       ('MMI PRO CIC', 'v3.3.7.mmipro.c', '3.3.7.mmipro.c',
        'https://drive.google.com/drive/folders/1CGC4iZoX2uvuiMUsA7AYp8n6roc602jJ', NULL, NULL, 1),
       ('MMI PRO NBT', 'v3.1.1.8R1.mmipro.b', '3.1.1.8R1.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.1.1.8R3.mmipro.b', '3.1.1.8R3.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.1.1.8R4.mmipro.b', '3.1.1.8R4.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.1.1.9.mmipro.b', '3.1.1.9.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.2.0.mmipro.b', '3.2.0.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.3.0.mmipro.b', '3.3.0.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.3.1.mmipro.b', '3.3.1.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.3.2.mmipro.b', '3.3.2.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.3.3.mmipro.b', '3.3.3.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.3.4.mmipro.b', '3.3.4.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.3.5.mmipro.b', '3.3.5.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.3.6.mmipro.b', '3.3.6.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f',
        'https://drive.google.com/drive/folders/1rCgqberGLDSj9yn2McHVDc-0ydphqHRw',
        'https://drive.google.com/drive/folders/1bd61AefAypTICA2PFfJw_5Ly3RCSRkqh', 0),
       ('MMI PRO NBT', 'v3.3.7.mmipro.b', '3.3.7.mmipro.b',
        'https://drive.google.com/drive/folders/1gwe0Bmq5m1V0oSGjCWDzPIlkqc7dqm3f', NULL, NULL, 1),
       ('MMI PRO EVO', 'v3.1.1.8R3.mmipro.e', '3.1.1.8R3.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.1.1.8R4.mmipro.e', '3.1.1.8R4.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.1.1.8R1.mmipro.e', '3.1.1.8R1.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.1.1.9.mmipro.e', '3.1.1.9.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.2.0.mmipro.e', '3.2.0.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.3.0.mmipro.e', '3.3.0.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.3.1.mmipro.e', '3.3.1.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.3.2.mmipro.e', '3.3.2.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.3.3.mmipro.e', '3.3.3.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.3.4.mmipro.e', '3.3.4.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.3.5.mmipro.e', '3.3.5.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.3.6.mmipro.e', '3.3.6.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3',
        'https://drive.google.com/drive/folders/1qsKnjRagUMDDJac6ek4rHwYmKEDOlxB7',
        'https://drive.google.com/drive/folders/1y2YKwsdAn9hllyBqcR_jPXIZh1CWuP1w', 0),
       ('MMI PRO EVO', 'v3.3.7.mmipro.e', '3.3.7.mmipro.e',
        'https://drive.google.com/drive/folders/1Mx1ysAA6_CL8Cx0dva4BSaiT_Bgsypb3', NULL, NULL, 1),
       ('LCI MMI Prime CIC', 'v3.4.1.mmiprixu.b', '3.4.1.mmiprixu.b', NULL,
        'https://drive.google.com/drive/folders/1Hl3h1Az7vYzCiUO9RD8x6mvbF_pFAqJS', NULL, 0),
       ('LCI MMI Prime CIC', 'v3.4.2.mmiprilci', '3.4.2.mmiprilci', NULL,
        'https://drive.google.com/drive/folders/1Hl3h1Az7vYzCiUO9RD8x6mvbF_pFAqJS', NULL, 0),
       ('LCI MMI Prime CIC', 'v3.4.4.mmiprilci', '3.4.4.mmiprilci', NULL, NULL, NULL, 1),
       ('LCI MMI Prime NBT', 'v3.4.1.mmiprixu.b', '3.4.1.mmiprixu.b', NULL, NULL,
        'https://drive.google.com/drive/folders/1y7pX-EiPzHtV9x29VregYmu8F9q6IGsG', 0),
       ('LCI MMI Prime NBT', 'v3.4.2.mmiprilci', '3.4.2.mmiprilci', NULL, NULL,
        'https://drive.google.com/drive/folders/1y7pX-EiPzHtV9x29VregYmu8F9q6IGsG', 0),
       ('LCI MMI Prime NBT', 'v3.4.4.mmiprilci', '3.4.4.mmiprilci', NULL, NULL, NULL, 1),
       ('LCI MMI Prime EVO', 'v3.4.1.mmiprixu.b', '3.4.1.mmiprixu.b', NULL, NULL,
        'https://drive.google.com/drive/folders/1cG7ECeagNhRDC0VybI-nkjW7MGxxqMDQ', 0),
       ('LCI MMI Prime EVO', 'v3.4.2.mmiprilci', '3.4.2.mmiprilci', NULL, NULL,
        'https://drive.google.com/drive/folders/1cG7ECeagNhRDC0VybI-nkjW7MGxxqMDQ', 0),
       ('LCI MMI Prime EVO', 'v3.4.4.mmiprilci', '3.4.4.mmiprilci', NULL, NULL, NULL, 1),
       ('LCI MMI PRO CIC', 'v3.4.1.mmiproxu.b', '3.4.1.mmiproxu.b', NULL,
        'https://drive.google.com/drive/folders/10QQWbjgQg_Gt5vZruZzJkeU_9qYg8YYn', NULL, 0),
       ('LCI MMI PRO CIC', 'v3.4.2.mmiprolci', '3.4.2.mmiprolci', NULL,
        'https://drive.google.com/drive/folders/10QQWbjgQg_Gt5vZruZzJkeU_9qYg8YYn', NULL, 0),
       ('LCI MMI PRO CIC', 'v3.4.4.mmiprolci', '3.4.4.mmiprolci', NULL, NULL, NULL, 1),
       ('LCI MMI PRO NBT', 'v3.4.1.mmiproxu.b', '3.4.1.mmiproxu.b', NULL, NULL,
        'https://drive.google.com/drive/folders/1vaffOAawGnKXnkEKcA6d39JhtOTLwfJV', 0),
       ('LCI MMI PRO NBT', 'v3.4.2.mmiprolci', '3.4.2.mmiprolci', NULL, NULL,
        'https://drive.google.com/drive/folders/1vaffOAawGnKXnkEKcA6d39JhtOTLwfJV', 0),
       ('LCI MMI PRO NBT', 'v3.4.4.mmiprolci', '3.4.4.mmiprolci', NULL, NULL, NULL, 1),
       ('LCI MMI PRO EVO', 'v3.4.1.mmiproxu.b', '3.4.1.mmiproxu.b', NULL, NULL,
        'https://drive.google.com/drive/folders/1Xgj1DXUHMbQON6Sm_wYB76H04HkYBNHV', 0),
       ('LCI MMI PRO EVO', 'v3.4.2.mmiprolci', '3.4.2.mmiprolci', NULL, NULL,
        'https://drive.google.com/drive/folders/1Xgj1DXUHMbQON6Sm_wYB76H04HkYBNHV', 0),
       ('LCI MMI PRO EVO', 'v3.4.4.mmiprolci', '3.4.4.mmiprolci', NULL, NULL, NULL, 1);
